from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml


DEFAULT_CONFIG: dict[str, Any] = {
    "sms_provider": "herosms_api",
    "sms_api_key": "",
    "sms_country": "187",
    "sms_service": "dr",
    "proxy": "",
    "proxy_jp": "",
    "lajiao_proxy_regions": "JP",
    "country_code": "1",
    "country_name": "United States",
    "use_camoufox": False,
    "headed": False,
    "browser_mode": "protocol",
    "browser_engine": "patchright",
    "browser_channel": "chrome",
    "browser_profile_mode": "per_task",
    "browser_no_viewport": True,
    "email_register_flow": "fast",
    "locale": "ja-JP",
    "timezone_id": "Asia/Tokyo",
    "accept_language": "ja-JP,ja;q=0.9,en-US;q=0.8,en;q=0.7",
    "sms_code_timeout": 600,
    "rotate_proxy_each_attempt": False,
    "lajiao_proxy_api_url": "http://api.lajiaohttp.com/api/extract_ip",
    "lajiao_proxy_num": 3,
    "lajiao_proxy_timeout": 15,
    "lajiao_proxy_mode": "api",
    "lajiao_proxy_credentials": "",
    "lajiao_proxy_credentials_file": "",
    "lajiao_proxy_expected_country": "",
    "camoufox_geoip": True,
    "camoufox_humanize": True,
    "camoufox_enable_cache": False,
    "iceaix_api_key": "",
    "iceaix_base_url": "https://plus.iceaix.com",
    "paypal_phone": "",
    "iceaix_sms_api": "",
    "iceaix_job_timeout": 300,
    "iceaix_poll_interval": 3,
    "iceaix_otp_timeout": 60,
    "iceaix_pplink_retry": 20,
    "iceaix_job_create_attempts": 3,
    "iceaix_proxy": "",
    "iceaix_proxy_jp": "",
    "iceaix_allow_paid_no_trial": False,
    "upi_activation_enabled": True,
    "upi_base_url": "https://upi.akkkkk.top",
    "upi_client_key": "",
    "upi_client_keys": [],
    "upi_default_channel": "upi",
    "upi_device_id": "gpt-register",
    "upi_submit_per_key_per_min": 50,
    "upi_poll_interval_sec": 5,
    "upi_poll_timeout_sec": 1800,
    "upi_auto_verify_plus": True,
    "plus_verify_retries": 6,
    "plus_verify_interval": 10,
    "outlook_email": "",
    "outlook_token_order_file": "",
    "outlook_web_otp": True,
    "outlook_password": "",
    "oauth_client_id": "app_EMoamEEZ73f0CkXaXp7hrann",
    "save_token_pool": False,
    "oauth_redirect_uri": "http://localhost:1455/auth/callback",
    "oauth_callback_mode": "cpa",
    "cpa_base_url": "",
    "cpa_management_key": "",
    "outlook_failed_retryable_limit": 2,
    "outlook_cooldown_hours": 24,
    "mailbox_provider": "icloud_api",
    "mailbox_domain": "",
    "mailbox_imap_user": "",
    "mailbox_imap_pass": "",
    "mailbox_imap_host": "",
    "mailbox_imap_port": 993,
    "cfworker_api_url": "",
    "cfworker_admin_token": "",
    "cfworker_domain": "",
    "cfworker_fingerprint": "",
    "icloud_api_order_file": "",
    "icloud_api_order_text": "",
    "outlook_max_attempts_per_run": 3,
    "herosms_cancel_on_timeout": False,
    "prepare_registration_before_phone": True,
    "precheck_phone_before_sms": True,
    "herosms_presend_cancel_delay": 75,
    "herosms_max_price": 0.0999,
    "sms_activation_pool_enabled": True,
    "sms_activation_release_grace_seconds": 120,
    "sms_activation_block_ttl_seconds": 86400,
    "sms_activation_pool_file": "",
    "sms_first_poll_delay": 12,
    "sms_poll_interval": 5,
    "sms_preserve_password_on_timeout": True,
    "email_otp_timeout": 300,
    "email_otp_poll_interval": 5,
    "sub2api_url": "",
    "sub2api_admin_key": "",
    "output_dir": "output",
    "save_session": True,
    "save_tokens": True,
    "max_parallel_tasks": 200,
    "max_register_tasks": 200,
    "max_oauth_tasks": 8,
    "max_maintenance_tasks": 8,
}


def load_config(path: str | Path = "config.yaml") -> dict[str, Any]:
    config = dict(DEFAULT_CONFIG)
    config_path = Path(path)
    if not config_path.exists():
        print(f"[!] 配置文件不存在: {path}，使用默认配置")
        return config
    with config_path.open("r", encoding="utf-8") as handle:
        user_config = yaml.safe_load(handle) or {}
    if isinstance(user_config, dict):
        config.update(user_config)
    return config
