export const PROVIDER_FIELD_LABELS: Record<string, string> = {
  service: '服务代码',
  countries: '支持地区',
  max_price: '最高价格',
  brazil_fixed_price: '巴西固定价',
  format: '数据格式',
  import: '导入说明',
  browser_bridge: '浏览器代理桥',
  source: '来源',
  reader: '读取方式',
  fields: '字段',
  api_modes: 'API 模式',
  sms_api_key: 'HeroSMS API Key',
  sms_service: '服务代码',
  sms_country: '接码国家',
  country_code: '手机号国家码',
  country_name: '国家名称',
  herosms_fixed_price: '固定价格',
  herosms_max_price: '最高价格',
  sms_phone_url: '手机号 API',
  sms_phone_urls: '批量手机号 API',
  sms_phone_url_file: '手机号 API 文件',
  lajiao_proxy_mode: '代理模式',
  lajiao_proxy_credential_protocol: '代理协议',
  lajiao_proxy_credentials: '代理账号',
  lajiao_proxy_credentials_file: '代理账号文件',
  lajiao_proxy_regions: '代理地区',
  lajiao_proxy_timeout: '代理超时',
  lajiao_proxy_api_url: '代理 API URL',
  outlook_token_order_file: 'Outlook Token 文件',
  icloud_api_order_file: 'iCloud API 邮箱文件',
  icloud_api_order_text: 'iCloud API 邮箱链接',
  icloud_privacy_order_file: 'iCloud 隐私邮箱文件',
  icloud_privacy_order_text: 'iCloud 隐私邮箱账号',
  outlook_email: 'Outlook 邮箱',
  outlook_password: 'Outlook 密码',
  oauth_client_id: 'OAuth Client ID',
  mailbox_domain: '邮箱域名',
  mailbox_imap_user: 'IMAP 用户',
  mailbox_imap_pass: 'IMAP 授权码',
  mailbox_imap_host: 'IMAP 主机',
  mailbox_imap_port: 'IMAP 端口',
  cfworker_api_url: 'CFWorker API 地址',
  cfworker_admin_token: 'CFWorker Token',
  cfworker_domain: 'CFWorker 域名',
}

export function providerFieldLabel(key: string): string {
  return PROVIDER_FIELD_LABELS[key] ?? key
}
